defaults:
  - _self_
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg: ${oc.env:GPU_ARCH,b300}tp${oc.env:TP}mbs${oc.env:MBS}

# skip_evals = floor(0.125 * trainer.global_batch_size + 2)
skip_evals: ${oc.decode:${oc.env:SKIP_EVALS,${floor:${add:${multiply:0.125,${trainer.global_batch_size}},2}}}}
load_ckpt: ${oc.decode:${oc.env:LOAD_CKPT,False}}
parallel_load: ${oc.decode:${oc.env:PARALLEL_LOAD,False}}
data_root: ${oc.decode:${oc.env:DATA_ROOT,/data}}
ckpt_root: ${oc.decode:${oc.env:CKPT_ROOT,/ckpt}}

trainer:
  devices: ${oc.decode:${oc.env:DGXNGPU,8}}
  num_nodes: ${oc.decode:${oc.env:DGXNNODES,1}}
  # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  max_steps: ${oc.decode:${oc.env:MAX_STEPS,null}}
  # val_check_interval = ceil(VAL_CHECK_INTERVAL / global_batch_size)
  val_check_interval: ${ceil_div:${oc.decode:${oc.env:VAL_CHECK_INTERVAL,384}},${trainer.global_batch_size}}
  limit_val_batches: ${oc.decode:${oc.env:LIMIT_VAL_BATCHES,1.0}}
  # batch size
  global_batch_size: ${floor_div:${multiply:${oc.decode:${oc.env:MINIBS,1}},${floor_div:${multiply:${trainer.devices},${trainer.num_nodes}},${multiply:${model.tensor_model_parallel_size},${model.pipeline_model_parallel_size}}}},${oc.decode:${oc.env:CP,1}}}
  micro_batch_size: ${oc.decode:${oc.env:MBS,1}}
  val_micro_batch_size: ${oc.decode:${oc.env:VAL_MBS,1}}
  val_global_batch_size: ${floor_div:${multiply:${oc.decode:${oc.env:VAL_MBS,1}},${floor_div:${multiply:${trainer.devices},${trainer.num_nodes}},${multiply:${model.tensor_model_parallel_size},${model.pipeline_model_parallel_size}}}},${oc.decode:${oc.env:CP_EVAL,${oc.env:CP,1}}}}
  log_every_n_steps: ${oc.decode:${oc.env:LOG_EVERY_N_STEPS,10}}

model:
  global_batch_size: ${trainer.global_batch_size}
  # model parallelism
  tensor_model_parallel_size: ${oc.decode:${oc.env:TP,1}}
  ub_tp_comm_overlap: ${oc.decode:${oc.env:TP_COMM_OVERLAP,False}}
  sequence_parallel: ${oc.decode:${oc.env:SP,False}}
  pipeline_model_parallel_size: ${oc.decode:${oc.env:PP,1}}
  context_parallel_size: ${oc.decode:${oc.env:CP,1}}
  cp_comm_type: ${oc.decode:${oc.env:CP_COMM_TYPE,'a2a'}}
  eval_cp: ${oc.decode:${oc.env:CP_EVAL,null}}
  # model configuration
  num_layers: ${oc.decode:${oc.env:OVERWRITTEN_NUM_LAYERS,80}}
  encoder_seq_length: ${oc.decode:${oc.env:MAX_SEQLEN,8192}}
  seed: ${oc.decode:${oc.env:SEED,1}}
  # first/last layers in bf16
  first_last_layers_bf16: ${oc.decode:${oc.env:FIRST_LAST_LAYERS_BF16,False}}
  num_layers_at_start_in_bf16: ${oc.decode:${oc.env:NUM_LAYERS_AT_START_IN_BF16,0}}
  num_layers_at_end_in_bf16: ${oc.decode:${oc.env:NUM_LAYERS_AT_END_IN_BF16,0}}
  # FP4
  fp4: ${oc.decode:${oc.env:FP4,False}}
  fp4_recipe: ${oc.decode:${oc.env:FP4_RECIPE,nvfp4}}
  fp4_param: ${oc.decode:${oc.env:FP4_PARAM,False}}
  # FP8
  fp8: ${oc.decode:${oc.env:FP8,True}}
  fp8_param_gather: ${oc.decode:${oc.env:FP8_PARAM_GATHER,False}}
  fp8_recipe: ${oc.decode:${oc.env:FP8_RECIPE,'delayed'}}
  fp8_amax_history_len: ${oc.decode:${oc.env:FP8_AMAX_HISTORY,128}} # Number of steps for which amax history is recorded per tensor
  fp8_amax_compute_algo: ${oc.env:FP8_AMAX_ALGO,most_recent} # 'most_recent' or 'max'. Algorithm for computing amax from history
  fp8_dot_product_attention: ${oc.decode:${oc.env:FP8_DPA,0}}
  reduce_amax: ${oc.decode:${oc.env:FP8_REDUCE_AMAX,False}}
  # FP4 -> FP8 healing settings
  healing_iter: ${oc.decode:${oc.env:HEALING_ITER,0}}
  healing_precision: ${oc.decode:${oc.env:HEALING_PRECISION,FP8_DS}} # Options: FP8_DS, MXFP8
  pre_quantized_model: ${oc.decode:${oc.env:PRE_QUANTIZED_MODEL,False}}
  store_gpu: ${oc.decode:${oc.env:STORE_GPU,False}}
  reset_cg_after_healing: ${oc.decode:${oc.env:RESET_CG_AFTER_HEALING,False}}
  # CUDA Graphs
  cuda_graph_scope: ${oc.decode:${oc.env:CUDA_GRAPH_SCOPE,'full_iteration'}}
  use_te_rng_tracker: ${oc.decode:${oc.env:USE_TE_RNG_TRACKER,True}}
  # CPU Offloading
  cpu_offloading: ${oc.decode:${oc.env:CPU_OFFLOADING,False}}
  cpu_offloading_num_layers: ${oc.decode:${oc.env:CPU_OFFLOADING_NUM_LAYERS,20}}
  cpu_offloading_double_buffering: ${oc.decode:${oc.env:CPU_OFFLOADING_DOUBLE_BUFFERING,False}}
  cpu_offloading_activations: True
  cpu_offloading_weights: False
  # Activation Recompute
  recompute_granularity: ${oc.decode:${oc.env:RECOMPUTE_GRANULARITY,null}}
  recompute_method: ${oc.decode:${oc.env:RECOMPUTE_METHOD,null}}
  recompute_num_layers: ${oc.decode:${oc.env:RECOMPUTE_NUM_LAYERS,null}}
  distribute_saved_activations: ${oc.decode:${oc.env:DISTRIBUTE_SAVED_ACTIVATIONS,False}}
  recompute_modules: ${oc.decode:${oc.env:RECOMPUTE_MODULES,null}}
  # Memory/Performance optimizations
  fused_single_qkv_rope: ${oc.decode:${oc.env:FUSED_SINGLE_QKV_ROPE,False}}
  fsdp: ${oc.decode:${oc.env:FSDP,null}}
  activation_func_fp8_input_store: ${oc.decode:${oc.env:FP8_ACT,0}}
  use_transformer_engine_op_fuser: ${oc.decode:${oc.env:USE_TE_OPS,False}}
  use_sharp: ${oc.decode:${oc.env:USE_SHARP,False}}
  gradient_accumulation_fusion: ${oc.decode:${oc.env:GRADIENT_ACCUMULATION_FUSION,True}}
  cross_entropy_loss_fusion: ${oc.decode:${oc.env:CROSS_ENTROPY_LOSS_FUSION,True}}
  cross_entropy_loss_fusion_impl: ${oc.decode:${oc.env:CROSS_ENTROPY_LOSS_FUSION_IMPL,'te'}}

  custom:
    warmup: ${oc.decode:${oc.env:WARMUP,False}}
    warmup_train_steps: ${oc.decode:${oc.env:WARMUP_TRAIN_STEPS,2}}
    warmup_validation_steps: ${oc.decode:${oc.env:WARMUP_VALIDATION_STEPS,2}}
    cuda_graph_warmup_steps: ${oc.decode:${oc.env:CUDA_GRAPH_WARMUP_STEPS,1}}
    reset_fp8_stats_after_warmup: ${oc.decode:${oc.env:RESET_FP8_STATS_AFTER_WARMUP,1}}

optim:
  lr: ${oc.decode:${oc.env:LR,0.0004}}
  use_distributed_optimizer: ${oc.decode:${oc.env:USE_DISTRIBUTED_OPTIMIZER,True}}
  overlap_param_gather_with_optimizer_step: ${oc.decode:${oc.env:OVERLAP_PARAM_GATHER_WITH_OPTIMIZER_STEP,False}}
  sched:
    warmup_steps: ${oc.decode:${oc.env:WARMUP_STEPS,0}}

ddp:
  overlap_grad_reduce: ${oc.decode:${oc.env:DDP_OVERLAP_GRAD_REDUCE,True}}
  overlap_param_gather: ${oc.decode:${oc.env:DDP_OVERLAP_PARAM_GATHER,True}}
  fp8_param_gather: ${oc.decode:${oc.env:FP8_PARAM_GATHER,False}}
  fp4_param_gather: ${oc.decode:${oc.env:FP4_PARAM_GATHER,False}}
  average_in_collective: ${oc.decode:${oc.env:DDP_AVERAGE_IN_COLLECTIVE,False}}
  nccl_ub: ${oc.decode:${oc.env:NCCL_UB,False}}
  bucket_size: ${oc.decode:${oc.env:BUCKET_SIZE,45000000}}

dataloader:
  num_workers: ${oc.decode:${oc.env:NUM_WORKERS,8}}


custom:
  target_log_ppl: ${oc.decode:${oc.env:TARGET_LOG_PPL,0.925}}
  force_success_status: ${oc.decode:${oc.env:FORCE_SUCCESS_STATUS,0}}

nsys_profile:
  enabled: ${oc.decode:${oc.env:PROFILE,False}}
  start_step: ${oc.decode:${oc.env:PROFILE_START_STEP,4}}
  end_step: ${oc.decode:${oc.env:PROFILE_END_STEP,8}}
  ranks_str: ${oc.env:PROFILE_RANKS,0}
  nvtx_ranges: ${oc.decode:${oc.env:BREAKDOWN,False}}
